CREATE TABLE topics (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(10) DEFAULT 'ACTIVE',
    author VARCHAR(100),
    course VARCHAR(100),
    PRIMARY KEY (id)
);